# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Miguel Cubas Lopez
title: Java Developer
email: mcubas1214@gmail.com
website: https://macl1214.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  macl1214
linkedin_username: miguel-cubas-lopez

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! My name is Miguel and I am a computer science graduate. I have experience in web apps through personal projects. I am currently seeking an entry position as a software developer to put my experience to the test and to further develop my skills in a software engineering team.

  I am most skilled in: <mark>Java</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Covid Cases Tracker
        link: github.com/sproogen
        # link_text: Project Website
          
        description: | # this will include new lines to allow paragraphs
          This was one of my first web applications that I developed using the Spring Framework. I wanted to create an app that tracked Covid cases in multiple countries around the world. Using a dataset found on Github, I developed this app that would make requests to the repo when needed to get the most recent Covid cases, then display it on the website.

          I was able to learn a lot of how to make HTTP requests using Java's HTTP Client API. To display the information, I utiized Thymeleaf pages with HTML/CSS and javascript.
      - layout: top-middle
        title: Student Management System
        link: github.com/sproogen
        # link_text: Project Website
          
        description: | # this will include new lines to allow paragraphs
          All universities have a self-service portal that gives their members the ability to log in and do various tasks. Because of this, I created my own to see all the details that go into making one. To create the app, I decided to use the service-repository design pattern as a way to handle separation of concerns. I designed the service layer to gather the data from the backend and convert it into DTOs to use in the frontend. 

          I used Java (Spring Framework) to develop the backend of the app, and used HTML/CSS and Javascript for the frontend. 

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:      
      - layout: left
        title: GDIT
        # link_text: boringcompany.com
        sub_title: Call Center Supervisor
        caption: October 2017 - December 2018
        description: | # this will include new lines to allow paragraphs
          Working as a supervisor at a disaster assistance helpine was my first leadership position in the professional setting. I led a team of 10 agents, frequently monitoring their calls and coaching them to help improve the assistance provided to the survivors. At times, I even stepped in on the call to provide further assistance, or to de-escalate the situations when needed.

      - layout: left
        title: Koons Tysons Toyota
        # link_text: boringcompany.com
        sub_title: Car Salesman
        caption: May 2015 - April 2017
        description: | # this will include new lines to allow paragraphs
          'Communication is the key success!' Working as a car salesman not only taught me how to hold a conversation with others, but how to effectively communicate. Listening to what the client was saying was the most important thing in the car business. I was able to improve on this skill with each client, and eventually, was able to see patterns with their wants and needs.

          This job really gave me the motivation to keep on working on myself.         


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Northern Virginia Community College
        caption: 20 - 2018
        sub_title: AS Computer Science
        description: | # this will include new lines to allow paragraphs
          When I first started attending NVCC, I had the intention of studying to become a Mechanical Engineer. After taking a few courses, I realized that it wasn't for me, and felt defeated. I took time off school, went into the work field, and eventually returned to school to study computer science, and realized that it was the right path for me

      - layout: left
        title: George Mason University
        caption: 2019 - 2020
        sub_title: BS Computer Science
        description: | # this will include new lines to allow paragraphs
          My time at George Mason was rather short. Due to Covid, my last year at Mason turned into online learning, which made it difficult to follow along with the classes. This also limited the availability of courses, but I was still able to sign up for some that I found interesting. 

          Outside of my courses, I was involved in Latin organizations and was part of a group called Azucar, a Latin dance group that held multiple classes every week.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interest in software engineering, I also enjoy:
      - Soccer
      - Gaming
      - Exercise (Currently getting into calisthenics!)
      - Hiking

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
